trigger:
- main

pool:
  name: RicardoPoolWin  # Nombre exacto de tu pool autohospedado

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: npm ci
  displayName: 'Install dependencies'

- script: npx playwright install --with-deps
  displayName: 'Install Playwright browsers'

- script: npm test
  displayName: 'Run E2E tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'test-results/**/*.xml'
    failTaskOnFailedTests: true
  condition: succeededOrFailed()
  displayName: 'Publish test results'

- script: |
    echo Creando archivo ZIP para despliegue...
    powershell -Command "Compress-Archive -Path *.html, css, js -DestinationPath drop.zip -Force"
  displayName: 'Crear ZIP de producción'
  condition: succeeded()  # Solo si los tests pasaron

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)/drop.zip'
    artifact: 'drop'
    publishLocation: 'pipeline'
  condition: succeeded()
  displayName: 'Publicar ZIP para Azure App Service'
